import { StyleSheet } from 'react-native';
import { colors } from '@/constants/colors';

export const CameraStyles = StyleSheet.create({
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  permText: { fontSize: 16, fontWeight: '600', marginTop: 16, marginBottom: 22, textAlign: 'center' },
  permBtn: { paddingVertical: 14, paddingHorizontal: 32, borderRadius: 14 },
  overlayTop: { position: 'absolute', top: 0, left: 0, right: 0, height: '18%', backgroundColor: 'rgba(0,0,0,0.58)' },
  overlayBottom: { position: 'absolute', bottom: 0, left: 0, right: 0, height: '22%', backgroundColor: 'rgba(0,0,0,0.58)' },
  overlayLeft: { position: 'absolute', top: '18%', bottom: '22%', left: 0, width: '4%', backgroundColor: 'rgba(0,0,0,0.58)' },
  overlayRight: { position: 'absolute', top: '18%', bottom: '22%', right: 0, width: '4%', backgroundColor: 'rgba(0,0,0,0.58)' },
  cardFrame: { position: 'absolute', top: '18%', bottom: '22%', left: '4%', right: '4%', borderWidth: 1.5, borderRadius: 8 },
  modeIndicator: {
    position: 'absolute',
    top: 50,
    left: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    zIndex: 10,
  },
  modeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  hint: { position: 'absolute', top: 100, alignSelf: 'center', backgroundColor: 'rgba(0,0,0,0.72)', flexDirection: 'row', alignItems: 'center', paddingVertical: 8, paddingHorizontal: 16, borderRadius: 20 },
  hintText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  controls: { position: 'absolute', bottom: 36, width: '100%', flexDirection: 'row', justifyContent: 'center', gap: 14, paddingHorizontal: 20 },
  cancelBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.error, paddingVertical: 13, paddingHorizontal: 15, borderRadius: 30, elevation: 4 },
  cancelText: { color: '#fff', fontWeight: '700', fontSize: 15 },
  captureBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 13, paddingHorizontal: 15, borderRadius: 30, elevation: 6 },
  captureText: { color: colors.navy, fontWeight: '700', fontSize: 15 },
});

// ─── Main Screen Styles ───────────────────────────────
export const scanStyles = StyleSheet.create({
  container: {
    flex: 1,
    
  },
  header: {
    backgroundColor: colors.navy,
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 26,
    position: 'relative',
    overflow: 'hidden',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerGlow: {
    position: 'absolute',
    top: -40,
    right: -30,
    width: 140,
    height: 130,
    borderRadius: 65,
    backgroundColor: colors.amber,
    opacity: 0.12,
  },
  greetText: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 3,
  },
  titleText: {
    color: colors.white,
    fontSize: 24,
    fontWeight: '800',
  },
  titleSpan: {
    color: colors.amber,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  scanOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 16,
    gap: 10,
  },
  optionBtn: {
    width: '18%',
    minWidth: 70,
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center',
    gap: 6,
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  optionIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  optionLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
  },
  optionSub: {
    fontSize: 9,
    color: colors.muted,
    fontWeight: '500',
  },
  processingBox: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 14,
    padding: 20,
    alignItems: 'center',
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  processingText: {
    marginTop: 12,
    fontWeight: '700',
    fontSize: 14,
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 12,
    width: '100%',
  },
  progressBar: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: 6,
    borderRadius: 3,
  },
  progressText: {
    fontSize: 12,
    fontWeight: '600',
    minWidth: 40,
  },
  list: {
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  card: {
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
    overflow: 'hidden',
  },
  cardImage: {
    width: '100%',
    height: 180,
  },
  dualImageContainer: {
    flexDirection: 'row',
    height: 180,
    width: '100%',
    position: 'relative',
  },
  dualImage: {
    flex: 1,
    height: '100%',
  },
  imageDivider: {
    width: 2,
    backgroundColor: colors.white,
    position: 'absolute',
    left: '50%',
    top: 0,
    bottom: 0,
    marginLeft: -1,
    zIndex: 2,
  },
  dualBadge: {
    position: 'absolute',
    top: 8,
    left: '50%',
    transform: [{ translateX: -45 }],
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    zIndex: 3,
  },
  dualBadgeText: {
    color: colors.navy,
    fontSize: 10,
    fontWeight: '700',
  },
  deleteBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(0,0,0,0.6)',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageActions: {
    position: 'absolute',
    top: 12,
    left: 12,
  },
  imageActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
  },
  imageActionText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '700',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    fontSize: 18,
    fontWeight: '800',
  },
  cardInfo: {
    flex: 1,
    marginLeft: 12,
  },
  cardName: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 2,
  },
  cardDetail: {
    fontSize: 12,
    fontWeight: '500',
  },
  details: {
    padding: 14,
    paddingTop: 0,
  },
  infoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  infoText: {
    fontSize: 11,
    fontWeight: '600',
  },
  section: {
    marginTop: 12,
    padding: 10,
    backgroundColor: colors.bg,
    borderRadius: 10,
    borderLeftWidth: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    flex: 1,
  },
  countBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
  },
  countText: {
    fontSize: 9,
    fontWeight: '700',
  },
  valueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  indexBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  indexText: {
    fontSize: 10,
    fontWeight: '700',
  },
  valueText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
  },
  rawButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 16,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1,
  },
  rawButtonText: {
    fontSize: 13,
    fontWeight: '700',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
    paddingHorizontal: 30,
  },
  emptyIcon: {
    width: 96,
    height: 96,
    borderRadius: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
    dragHint: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    marginBottom: 8,
    gap: 6,
  },
  dragHintText: {
    fontSize: 12,
    fontStyle: 'italic',
  },
  fieldsList: {
    paddingBottom: 8,
  },
  draggableItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    marginVertical: 4,
    backgroundColor: colors.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  fieldIcon: {
    width: 28,
    height: 28,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  fieldContent: {
    flex: 1,
  },
  fieldType: {
    fontSize: 10,
    fontWeight: '600',
    marginBottom: 2,
  },
  fieldValue: {
    fontSize: 13,
    fontWeight: '400',
  },
  copyFieldBtn: {
    padding: 6,
    marginRight: 4,
  },
  dragHandle: {
    padding: 4,
  },
});