import { StyleSheet } from 'react-native';
import { colors } from '@/constants/colors';

export const settingsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.navy,
  },
  body: {
    flex: 1,
  },
  // Profile Hero
  profileHero: {
    backgroundColor: colors.navy,
    position: 'relative',
    overflow: 'hidden',
    paddingBottom: 28,
  },
  heroGlow: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: colors.amber,
    opacity: 0.18,
  },// Add these to your settingsStyles object
saveButtonDisabled: {
  opacity: 0.5,

},

  heroTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 20,
    paddingBottom: 18,
  },
  heroTitle: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '800',
  },
  heroEdit: {
    width: 36,
    height: 36,
    backgroundColor: 'rgba(245,159,10,0.18)',
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroBody: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: 24,
  },
  avatarWrap: {
    position: 'relative',
  },
  avatar: {
    width: 68,
    height: 68,
    backgroundColor: colors.amber,
    borderRadius: 34,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  avatarText: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.navy,
  },
  avatarEdit: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 22,
    height: 22,
    backgroundColor: colors.amber,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.navy,
  },
  heroInfo: {
    flex: 1,
  },
  heroName: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '800',
  },
  heroEmail: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    marginTop: 3,
  },
  heroBadges: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 3,
    paddingHorizontal: 9,
    borderRadius: 20,
  },
  badgeAmber: {
    backgroundColor: colors.amber,
  },
  badgeGreen: {
    backgroundColor: colors.partnerBg,
  },
  badgeTextAmber: {
    color: colors.navy,
    fontSize: 10,
    fontWeight: '700',
  },
  badgeTextGreen: {
    color: colors.partner,
    fontSize: 10,
    fontWeight: '700',
  },
  // Mini Stats
  miniStats: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginVertical: 16,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  miniStat: {
    flex: 1,
    backgroundColor: colors.white,
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.text,
  },
  statLabel: {
    fontSize: 10,
    color: colors.muted,
    fontWeight: '500',
    marginTop: 2,
  },
  // Section Label
  sectionLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 6,
  },
  // Form Card
  formCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    marginHorizontal: 16,
    marginBottom: 14,
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  formInner: {
    padding: 18,
  },
  formRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
  },
  formGroup: {
    flex: 1,
    marginBottom: 14,
  },
  formLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 5,
  },
  formInput: {
    width: '100%',
    backgroundColor: colors.bg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 11,
    padding: 12,
    fontSize: 13,
    color: colors.text,
    fontWeight: '600',
  },
  saveButton: {
    backgroundColor: colors.amber,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingVertical: 14,
    borderRadius: 13,
    shadowColor: colors.amber,
    shadowOpacity: 0.32,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 5 },
    elevation: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  saveButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: colors.navy,
  },
  // Subscription Card
  subCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 18,
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  subTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  subIcon: {
    width: 42,
    height: 42,
    backgroundColor: colors.amberLight,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.text,
  },
  subSubtitle: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: '500',
    marginTop: 1,
  },
  progressLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 11,
    fontWeight: '600',
    color: colors.muted,
    marginBottom: 7,
  },
  progressLabelStrong: {
    color: colors.text,
    fontWeight: '800',
  },
  progressBar: {
    backgroundColor: colors.border,
    borderRadius: 20,
    height: 7,
    overflow: 'hidden',
    marginBottom: 14,
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.amber,
    borderRadius: 20,
    width: '56%',
  },
  upgradeButton: {
    backgroundColor: colors.navy,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 13,
    borderRadius: 13,
  },
  upgradeButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.amber,
  },
  // Menu Card
  menuCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    marginHorizontal: 16,
    marginBottom: 14,
    shadowColor: colors.text,
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  menuIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuIconAmber: {
    backgroundColor: colors.amberLight,
  },
  menuIconRed: {
    backgroundColor: colors.redBg,
  },
  menuText: {
    flex: 1,
  },
  menuLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  menuLabelRed: {
    color: colors.red,
  },
  menuSub: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: '500',
    marginTop: 1,
  },
  chevron: {
    color: colors.textLight,
    fontSize: 12,
  },
  toggle: {
    width: 42,
    height: 24,
    backgroundColor: colors.amber,
    borderRadius: 20,
    position: 'relative',
  },
  toggleDot: {
    width: 18,
    height: 18,
    backgroundColor: colors.white,
    borderRadius: 9,
    position: 'absolute',
    top: 3,
    right: 3,
    shadowColor: colors.text,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 2,
  },
  // Version Footer
  versionFooter: {
    textAlign: 'center',
    paddingVertical: 8,
    paddingBottom: 14,
    fontSize: 10,
    color: colors.textLight,
  },
  // Toast
  toast: {
    position: 'absolute',
    top: 60,
    alignSelf: 'center',
    backgroundColor: colors.toastBg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 20,
    zIndex: 999,
    shadowColor: colors.text,
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 5,
  },
  toastText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '700',
  },
});